engines:
  rubocop:
    enabled: true
    channel: rubocop-0-48
  markdownlint:
    enabled: true
  bundler-audit:
    enabled: false
  fixme:
    enabled: true

ratings:
  paths:
  - bin/**
  - lib/**
  - "**.rb"
exclude_paths:
  - test/**
