AllCops:
  TargetRubyVersion: 2.2
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/UnneededCapitalW:
  Enabled: false
Style/MethodDefParentheses:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Enabled: false
